#服务器配置
server:
  port: 80
  
spring:
  #springboot整合durid数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/train?characterEncoding=utf8&useSSL=false
    username: root
    password: sorry
    driver-class-name: com.mysql.jdbc.Driver
  #springboot整合jsp
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #springboot整合redis
  redis:
    host: localhost
    port: 6379
    
#springboot整合mybatis
mybatis:
  config-location: classpath:mapper/config/sqlMapConfig.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.whl.domain
#pageHelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#配置通用mapper
mapper:
  identity: MYSQL
  not-empty: false
  mappers:
        - com.whl.util.mapper.MyMapper


  
  