spring:
  #决定使用哪个配置文件
  profiles:
    active: dev
  #springboot整合durid数据源
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/train?characterEncoding=utf8&useSSL=false
#    username: root
#    password: sorry
#    driver-class-name: com.mysql.jdbc.Driver
  #springboot整合jsp
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #springboot整合redis
  redis:
    host: localhost
    port: 6379
    
#springboot整合mybatis
mybatis:
  config-location: classpath:mapper/config/sqlMapConfig.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.whl.domain
#pageHelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#配置通用mapper
mapper:
  identity: MYSQL
  not-empty: false
  mappers:
        - com.whl.util.mapper.MyMapper

customer:
  username: whling
  age: 21

    
jdbc: 
  master:
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://hadoop01:3306/train?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: sorry
  slave01:
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://hadoop02:3306/train?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: sorry
  slave02: 
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://hadoop03:3306/train?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: sorry
  
  
